### PR TITLE
Ensure deletion of captured images when gif-screencast-autoremove-screenshots equals t

### PR DESCRIPTION
**Pull request by takaxp**
This PR is created to fix an issue on autoremove of screenshots regarding #6.
Tested in Ubuntu and also macOS.

### CODE REVIEW

**Comment by takaxp** [comment]
Could you please check this change if it will bring some new issues when (setq gif-screencast-want-optimized t) and gifsicle is actually avaliaable?

**Comment by Ambrevar** [comment]
This does not work: if both `gif-screencast-want-optimized` and `gif-screencast-autoremove-screenshots` are non-nil, then optimization won't run.

I suggest the following

```diff
@@ -191,21 +191,20 @@ If you are a macOS user, \"ppm\" should be specified."
                       ;; Delays must come after the file arguments.
                       (apply 'nconc delays)
                       (list output))))
-      (if gif-screencast-want-optimized
-          (set-process-sentinel p (lambda (process event)
-                                    (if (and (eq (process-status process) 'exit)
-                                             (= (process-exit-status process) 0))
-                                        (setq p (gif-screencast-optimize output))
-                                      (gif-screencast-print-status process event))))
-        (set-process-sentinel p 'gif-screencast-print-status))
-      (if gif-screencast-autoremove-screenshots
-          (set-process-sentinel p (lambda (process event)
-                                    (if (and (eq (process-status process) 'exit)
-                                             (= (process-exit-status process) 0))
-                                        (dolist (f gif-screencast--frames)
-                                          (delete-file (cdr f))))
-                                    (gif-screencast-print-status process event)))
-        (set-process-sentinel p 'gif-screencast-print-status)))))
+      (set-process-sentinel p 'gif-screencast--generate-gif-sentinel))))
+
+(defun gif-screencast--generate-gif-sentinel (process event)
+  (if gif-screencast-want-optimized
+      (if (and (eq (process-status process) 'exit)
+               (= (process-exit-status process) 0))
+          (let ((p (gif-screencast-optimize output)))
+            (set-process-sentinel p 'gif-screencast-print-status))
+        (gif-screencast-print-status process event)))
+  (if gif-screencast-autoremove-screenshots
+      (if (and (eq (process-status process) 'exit)
+               (= (process-exit-status process) 0))
+          (dolist (f gif-screencast--frames)
+            (delete-file (cdr f))))))
```

**Comment by Ambrevar** [comment]
I haven't tested the above, it's only a sketch to give you an idea.

Also could you rebase your branch on master? Thanks! :)

**Comment by Ambrevar** [comment]
Why did you close this?

**Comment by takaxp** [comment]
I propose the following changes but I'll recreate PR that will not includes previous commits on my master branch.
This code was tested in Ubuntu with gifsicle, and macOS.

```
      (setq p (apply 'start-process
                     gif-screencast-convert-program
                     (get-buffer-create gif-screencast-log)
                     gif-screencast-convert-program
                     (append
                      gif-screencast-convert-args
                      (mapcar 'cdr gif-screencast--frames)
                      ;; Delays must come after the file arguments.
                      (apply 'nconc delays)
                      (list output))))
      (set-process-sentinel p (lambda (process event)
                                (gif-screencast-print-status process event)
                                (when (and gif-screencast-want-optimized
                                           (eq (process-status process) 'exit)
                                           (= (process-exit-status process) 0))
                                  (gif-screencast-optimize output))
                                (when (and gif-screencast-autoremove-screenshots
                                           (eq (process-status process) 'exit)
                                           (= (process-exit-status process) 0))
                                  (dolist (f gif-screencast--frames)
                                    (delete-file (cdr f)))))))))
```

**Comment by Ambrevar** [comment]
Most of the time there is no need to re-create a PR, you can force-push
on the branch that was submitted in the request.

**Comment by takaxp** [comment]
OK,,,, I'm little confusing but I just push my new commit now.

**Comment by takaxp** [comment]
The reason why I could not use your proposal is that the `output` variable is not available in `gif-screencast--generate-gif-sentinel` :)

**Comment by Ambrevar** [comment]
Between two drafts I forgot to create a closure in one.  Basically you could put the lambda in another function that creates the closure over `output`.  No big deal, a lambda alone is fine too.

**Comment by takaxp** [comment]
I think I didn't do right things on my master branch as you expected...
Please let me know exactly what I should do. And it is OK for me even if you close this PR and just integrate the code as discussed in this page into your repository by copy & paste.

**Comment by Ambrevar** [comment]
I've cherry-picked the target commit and merged.

As for my recommendation: generally speaking it's nice if you make it as easy as possible for the maintainer to merge your pull request.
That means a linear, well written history of atomic commits.

After you previous pull request, you should have merged my master onto your master so that both histories would have been equivalent.  Then you would have created a new branch from master and added the single commit there which I just merged.

See the `git rebase(1)` man page.

**Comment by takaxp** [comment]
Yes, true. Thank you for your kind advice. Now I understand what was happened.
I have some additional PRs so I hope I'll do the right operations at next time :)

**Pull request closed without merging**
